### ISSUE TITLE
Maximum image size slider in photoswipe plugin is 2050px, but Koken supports larger images

### ISSUE THREAD

**Issue by laklare** [DanielMuller/koken-plugin-photoswipe#23]
Would it be possible to increase the maximum setting for the slider in the plugin configuration page to support the huge.2x Koken resolution of 4096px in case visitors are using 4K monitors?

**Comment by DanielMuller** [comment]
If your monitor is "High Density" and you are checked the "HiDPI" option in Koken's settings, you should already get the huge.2x images. "Huge" (2048px) is used for every device with a real pixel dimension of 2048 and above. "huge.2x" is used for devices with a devicePixelRatio>1.3.
I don't have access to this kind of screen, what are the values of `window.innerWidth`and `window.devicePixelRatio` on the target screen?

**Comment by risottto** [comment]
I've been trying to get the 4096 image zoom to work on my website with photoswipe as well. I have found that it works perfectly when the browser is on my macbook retina screen where the `window.devicePixelRatio`  is 2 (zoomed in images show up as 4000+ pixels, perfect for zooming in on artwork!

However the same image loaded on my 30" 2560x1600 NEC with a `window.devicePixelRatio` of 1, maxes out at 1600px (large, long ledge), this makes zoom almost useless, since my browser window is larger than the zoomed in image size, and the zoom button actually makes the image smaller!

Any way of tricking koken to serving the huge.2x image regardless of what pixelratio it detects on the current screen?

ps you can use this test page to find your `window.devicePixelRatio` for your current screen http://www.quirksmode.org/m/tests/widthtest.html

thanks!

Stan

**Comment by DanielMuller** [comment]
I wanted to avoid to use "2x" images for non-retina displays. But I guess there is no other way to accommodate for this kind of big screens.
