### ISSUE TITLE
Image Download Support

### ISSUE THREAD

**Issue by softcat** [DanielMuller/koken-plugin-photoswipe#29]
Hello,

I've got a problem getting the image download links working. If I enable the option in the plugin settings it generates  an empty
`<a href="" target="_blank" class="pswp__share--download" download="">Download Image</a>`
link. 

If i have a look in
`/koken/storage/plugins/photoswipe/pswp/pswp.min.js`
it says
`download:{id:"download",label:"Download Image",url:"",download:true}}`

If I change this to
`download:{id:"download",label:"Download Image",url:"{{raw_image_url}}",download:true}}`

I can get it basically working but this of course does not reflect the koken image download settings normally available through the lens tags

[http://help.koken.me/customer/portal/articles/828690-lens-tags#kokenmax_download](url) 

Can you give a hint how to implement this functionality?

**Comment by DanielMuller** [comment]
I never implemented to download link since I never had the need to use it.
You are right, url needs to be {{raw_image_url}}. This is a Photoswipe feature and has nothing to do with Lense Tags, which is a Koken Template variable.
The issue with using {{raw_image_url}}, is that it will download the current image (dependant on screen size) instead of the biggest image.

What's your opinion on this, should the link download the current image or the biggest image (huge.2x version)?

**Comment by DanielMuller** [comment]
I finally decided to leave the choice to the end user and added a plugin option, with default to "current size".
